---

- id: gls-xmlformat
  name: GLS XML Formatter
  description: >
    Formats XML files according GLS formating rules
  entry: localhost/xmlformat 
  language: docker_image
  require_serial: true
  