---
- id: xmlformat_docker
  name: XML Formatter (docker)
  description: >
    Formats XML files according GLS formating rules
  entry: quay.io/someth2say/xmlformat:0.3
  types: [xml]
  language: docker_image
  require_serial: true

- id: xmlformat_ruby
  name: XML Formatter (ruby)
  description: >
    Formats XML files according GLS formating rules
  entry: bin/xmlformat_rb.sh
  args: []
  types: [xml]
  language: script
  require_serial: true

- id: xmlformat_perl
  name: XML Formatter (perl)
  description: >
    Formats XML files according GLS formating rules
  entry: bin/xmlformat_pl.sh
  args: []
  types: [xml]
  language: script
  require_serial: true

